include: package:very_good_analysis/analysis_options.3.1.0.yaml

linter:
  rules:
    sort_pub_dependencies: false
    no_leading_underscores_for_local_identifiers: false
    public_member_api_docs: false
