include: package:flutter_lints/flutter.yaml

linter:
  rules:
    depend_on_referenced_packages: false

analyzer:
  exclude:
    - "build/**"

    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"
    - "**/*.widgetbook.dart"
