# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  release:
    branches:
      - main

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main # required!

      - name: ">> Flutter package <<"
        uses: k-paxian/dart-package-publisher@master
        with:
          force: true
          flutter: true
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
